services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: myapp_development
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: ["rails", "server", "-b", "0.0.0.0"]
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://myuser:mypassword@db:5432/myapp_development"

volumes:
  postgres_data:
