default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["POSTGRES_USER"] || "myuser" %>
  password: <%= ENV["POSTGRES_PASSWORD"] || "mypassword" %>
  host: localhost

development:
  <<: *default
  database: myapp_development
  host: localhost

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: myapp_production
